#! /bin/bash

# Small script that outputs the number of pages in a folder of OpenOffice documents
# This script is based on page 7 of the book Wicked Cool Shell Scripts 
# by Dave Taylor and Brandon Perry

echo "$(exiftool *.odt | grep Page-count | cut -d ":" -f2 | tr '\n' '+')""0" | bc
